
[build]
  # Usamos el comando estándar de Angular para el build de producción
  command = "npm run build"
 
  publish = "dist/administrador-presupuestos/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200